/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cal;

public class Cal_App extends javax.swing.JFrame {

    private String expression = "";

    /**
     * Creates new form Cal_App
     */
    public Cal_App() {
        initComponents();
    }

    private void append(String value) {
        expression += value;
        displayTf.setText(expression);
    }

    private double evaluateExpression(String expr) {

        java.util.Stack<Double> numbers = new java.util.Stack<>();
        java.util.Stack<Character> operators = new java.util.Stack<>();

        for (int i = 0; i < expr.length(); i++) {

            char ch = expr.charAt(i);

            // If digit or dot → build number
            if (Character.isDigit(ch) || ch == '.') {
                StringBuilder sb = new StringBuilder();

                while (i < expr.length()
                        && (Character.isDigit(expr.charAt(i)) || expr.charAt(i) == '.')) {

                    sb.append(expr.charAt(i));
                    i++;
                }
                i--;

                numbers.push(Double.parseDouble(sb.toString()));
            } // If operator
            else if (ch == '+' || ch == '-' || ch == '*' || ch == '/') {

                while (!operators.isEmpty()
                        && precedence(operators.peek()) >= precedence(ch)) {

                    double b = numbers.pop();
                    double a = numbers.pop();
                    char op = operators.pop();

                    numbers.push(applyOperation(a, b, op));
                }

                operators.push(ch);
            }
        }

        // Remaining operations
        while (!operators.isEmpty()) {
            double b = numbers.pop();
            double a = numbers.pop();
            char op = operators.pop();

            numbers.push(applyOperation(a, b, op));
        }

        return numbers.pop();
    }

    private int precedence(char op) {
        if (op == '+' || op == '-') {
            return 1;
        }
        if (op == '*' || op == '/') {
            return 2;
        }
        return 0;
    }

    private double applyOperation(double a, double b, char op) {

        switch (op) {
            case '+':
                return a + b;
            case '-':
                return a - b;
            case '*':
                return a * b;
            case '/':
                if (b == 0) {
                    throw new ArithmeticException("Divide by zero");
                }
                return a / b;
        }

        return 0;
    }

    private String formatResult(double value) {

        // If value is very large or very small → scientific notation
        if (Math.abs(value) >= 1e14 || (Math.abs(value) > 0 && Math.abs(value) < 1e-13)) {

            java.text.DecimalFormat sci = new java.text.DecimalFormat("0.############E0");
            sci.setMaximumFractionDigits(8); // adjust precision if needed
            return sci.format(value);
        }

        // Normal formatting
        java.text.DecimalFormat normal = new java.text.DecimalFormat("0.##############");
        normal.setMaximumFractionDigits(12);
        return normal.format(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        displayTf = new javax.swing.JTextField();
        percentBtn = new javax.swing.JButton();
        squareBtn = new javax.swing.JButton();
        sqrtBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        num7btn = new javax.swing.JButton();
        num8btn = new javax.swing.JButton();
        num9btn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        num4btn = new javax.swing.JButton();
        num5btn = new javax.swing.JButton();
        num6btn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        num1btn = new javax.swing.JButton();
        num2btn = new javax.swing.JButton();
        num3btn = new javax.swing.JButton();
        mulBtn = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        num0btn = new javax.swing.JButton();
        divBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        displayTf.setBackground(new java.awt.Color(0, 0, 0));
        displayTf.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        displayTf.setForeground(new java.awt.Color(255, 255, 255));
        displayTf.setText("0");

        percentBtn.setBackground(new java.awt.Color(153, 153, 153));
        percentBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        percentBtn.setForeground(new java.awt.Color(0, 0, 0));
        percentBtn.setText("%");
        percentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentBtnActionPerformed(evt);
            }
        });

        squareBtn.setBackground(new java.awt.Color(153, 153, 153));
        squareBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        squareBtn.setForeground(new java.awt.Color(0, 0, 0));
        squareBtn.setText("x²");
        squareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareBtnActionPerformed(evt);
            }
        });

        sqrtBtn.setBackground(new java.awt.Color(153, 153, 153));
        sqrtBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sqrtBtn.setForeground(new java.awt.Color(0, 0, 0));
        sqrtBtn.setText("√x");
        sqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(255, 102, 102));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(0, 0, 0));
        clearBtn.setText("CE");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        num7btn.setBackground(new java.awt.Color(102, 102, 102));
        num7btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num7btn.setForeground(new java.awt.Color(0, 0, 0));
        num7btn.setText("7");
        num7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7btnActionPerformed(evt);
            }
        });

        num8btn.setBackground(new java.awt.Color(102, 102, 102));
        num8btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num8btn.setForeground(new java.awt.Color(0, 0, 0));
        num8btn.setText("8");
        num8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8btnActionPerformed(evt);
            }
        });

        num9btn.setBackground(new java.awt.Color(102, 102, 102));
        num9btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num9btn.setForeground(new java.awt.Color(0, 0, 0));
        num9btn.setText("9");
        num9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9btnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(153, 153, 153));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("+");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        num4btn.setBackground(new java.awt.Color(102, 102, 102));
        num4btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num4btn.setForeground(new java.awt.Color(0, 0, 0));
        num4btn.setText("4");
        num4btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4btnActionPerformed(evt);
            }
        });

        num5btn.setBackground(new java.awt.Color(102, 102, 102));
        num5btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num5btn.setForeground(new java.awt.Color(0, 0, 0));
        num5btn.setText("5");
        num5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5btnActionPerformed(evt);
            }
        });

        num6btn.setBackground(new java.awt.Color(102, 102, 102));
        num6btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num6btn.setForeground(new java.awt.Color(0, 0, 0));
        num6btn.setText("6");
        num6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6btnActionPerformed(evt);
            }
        });

        subBtn.setBackground(new java.awt.Color(153, 153, 153));
        subBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subBtn.setForeground(new java.awt.Color(0, 0, 0));
        subBtn.setText("-");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        num1btn.setBackground(new java.awt.Color(102, 102, 102));
        num1btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num1btn.setForeground(new java.awt.Color(0, 0, 0));
        num1btn.setText("1");
        num1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1btnActionPerformed(evt);
            }
        });

        num2btn.setBackground(new java.awt.Color(102, 102, 102));
        num2btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num2btn.setForeground(new java.awt.Color(0, 0, 0));
        num2btn.setText("2");
        num2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2btnActionPerformed(evt);
            }
        });

        num3btn.setBackground(new java.awt.Color(102, 102, 102));
        num3btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num3btn.setForeground(new java.awt.Color(0, 0, 0));
        num3btn.setText("3");
        num3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3btnActionPerformed(evt);
            }
        });

        mulBtn.setBackground(new java.awt.Color(153, 153, 153));
        mulBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mulBtn.setForeground(new java.awt.Color(0, 0, 0));
        mulBtn.setText("*");
        mulBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulBtnActionPerformed(evt);
            }
        });

        dotBtn.setBackground(new java.awt.Color(153, 153, 153));
        dotBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dotBtn.setForeground(new java.awt.Color(0, 0, 0));
        dotBtn.setText(".");
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });

        num0btn.setBackground(new java.awt.Color(102, 102, 102));
        num0btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num0btn.setForeground(new java.awt.Color(0, 0, 0));
        num0btn.setText("0");
        num0btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0btnActionPerformed(evt);
            }
        });

        divBtn.setBackground(new java.awt.Color(153, 153, 153));
        divBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        divBtn.setForeground(new java.awt.Color(0, 0, 0));
        divBtn.setText("/");
        divBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtnActionPerformed(evt);
            }
        });

        equalBtn.setBackground(new java.awt.Color(255, 204, 51));
        equalBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equalBtn.setForeground(new java.awt.Color(0, 0, 0));
        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Designed by Imesh D. Perera");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Cal 2.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayTf)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(percentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(squareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sqrtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(num7btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(num0btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(divBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(num1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(num2btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(num4btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(num5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(num6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(num3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mulBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayTf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squareBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqrtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num0btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("About");

        jMenuItem3.setText("App developed by Imesh Perera");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("View Help");
        jMenu2.add(jMenuItem2);

        jMenu3.setText("About Calculator");

        jMenuItem4.setText("This is Cal 2.0");
        jMenu3.add(jMenuItem4);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num0btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0btnActionPerformed
        append("0");
    }//GEN-LAST:event_num0btnActionPerformed

    private void num1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1btnActionPerformed
        append("1");
    }//GEN-LAST:event_num1btnActionPerformed

    private void num2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2btnActionPerformed
        append("2");
    }//GEN-LAST:event_num2btnActionPerformed

    private void num3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3btnActionPerformed
        append("3");
    }//GEN-LAST:event_num3btnActionPerformed

    private void num4btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4btnActionPerformed
        append("4");
    }//GEN-LAST:event_num4btnActionPerformed

    private void num5btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5btnActionPerformed
        append("5");
    }//GEN-LAST:event_num5btnActionPerformed

    private void num6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6btnActionPerformed
        append("6");
    }//GEN-LAST:event_num6btnActionPerformed

    private void num7btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7btnActionPerformed
        append("7");
    }//GEN-LAST:event_num7btnActionPerformed

    private void num8btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8btnActionPerformed
        append("8");
    }//GEN-LAST:event_num8btnActionPerformed

    private void num9btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9btnActionPerformed
        append("9");
    }//GEN-LAST:event_num9btnActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        append("+");
    }//GEN-LAST:event_addBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        append("-");
    }//GEN-LAST:event_subBtnActionPerformed

    private void mulBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulBtnActionPerformed
        append("*");
    }//GEN-LAST:event_mulBtnActionPerformed

    private void divBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtnActionPerformed
        append("/");
    }//GEN-LAST:event_divBtnActionPerformed

    private void percentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentBtnActionPerformed
        try {
            // If expression contains operator
            if (expression.contains("/")) {

                String[] parts = expression.split("/");

                double first = Double.parseDouble(parts[0]);
                double second = Double.parseDouble(parts[1]);

                double result = (first / second) * 100;

                expression = String.format("%.2f", result);
                displayTf.setText(expression + " %");

            } else {
                // fallback normal percentage
                double value = Double.parseDouble(displayTf.getText());
                value = value / 100;
                expression = formatResult(value);
                displayTf.setText(expression);
            }

        } catch (Exception e) {
            displayTf.setText("Error");
            expression = "";
        }
    }//GEN-LAST:event_percentBtnActionPerformed

    private void squareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareBtnActionPerformed
        try {
            double value = Double.parseDouble(displayTf.getText());
            value = value * value;
            expression = formatResult(value);
            displayTf.setText(expression);
        } catch (Exception e) {
            displayTf.setText("Error");
            expression = "";
        }
    }//GEN-LAST:event_squareBtnActionPerformed

    private void sqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtBtnActionPerformed
        try {
            double value = Double.parseDouble(displayTf.getText());

            if (value < 0) {
                displayTf.setText("Error");
                expression = "";
                return;
            }

            value = Math.sqrt(value);
            expression = formatResult(value);
            displayTf.setText(expression);
        } catch (Exception e) {
            displayTf.setText("Error");
            expression = "";
        }
    }//GEN-LAST:event_sqrtBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        expression = "";
        displayTf.setText("0");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        try {
            double result = evaluateExpression(expression);
            expression = formatResult(result);
            displayTf.setText(expression);
        } catch (Exception e) {
            displayTf.setText("Error");
            expression = "";
        }
    }//GEN-LAST:event_equalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cal_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cal_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cal_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cal_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cal_App().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField displayTf;
    private javax.swing.JButton divBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mulBtn;
    private javax.swing.JButton num0btn;
    private javax.swing.JButton num1btn;
    private javax.swing.JButton num2btn;
    private javax.swing.JButton num3btn;
    private javax.swing.JButton num4btn;
    private javax.swing.JButton num5btn;
    private javax.swing.JButton num6btn;
    private javax.swing.JButton num7btn;
    private javax.swing.JButton num8btn;
    private javax.swing.JButton num9btn;
    private javax.swing.JButton percentBtn;
    private javax.swing.JButton sqrtBtn;
    private javax.swing.JButton squareBtn;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
